feature_list:
    - c_us_national_unemployment_rate__value_mavg_900_changeperc_180 #=> No need for this transformation
    #- c_fed_funds_rate__value_mavg_120_changeperc_180 #=> No need for this transformation
    #- c_industrial_production__value_mavg_180_changeperc_180 #=> No need for this transformation
    - c_capacity_utilization__value_mavg_600_changeperc_180 #=> No need for this transformation
    ##- c_us_national_unemployment_rate__value
    #- c_fed_funds_rate__value # leave this out
    ##- c_industrial_production__value
    ##- c_capacity_utilization__value
    - c_us_inflation_rate_monthly__value
    # - c_usa_bond_10year__open => Makes it worse
    # - c_usa_bond_2year__open => Makes it worse
    # - c_vix__close => Makes it worse
    - c_ted_spread_credit_risk__value_mavg_180
    #- c_sugar_prices__value

table_name: "prepped_20210516"
target: "c_bearmarket_days__value"
models: xgboostclassifier
  #"xgboostclassifier"
  #"logisticregression"
  #linearmodel:
  #  linearmodel__normalize:
  #    - "False"
  #    - "True"
  #knn:
  #  k:
  #    - 3
  #    - 8
  #  range: "false"
  #randomforestclassifier:
  #  max_depth:
  #    - 5
  #  n_estimators:
  #    - 30
  #xgboostregressor:
  #  xgboostregressor__eta:
  #    - 0.01
  #  xgboostregressor__max_depth:
  #    - 15
  #  xgboostregressor__booster:
  #    - 'gbtree'
  #    #- 'gblinear'
  #  xgboostregressor__min_child_weight:
  #    - 6