feature_list:
  - "bond_spread"
  - "c_leitzins_usa__value"
  - "c_ted_spread_credit_risk__value"
  - "c_futures_sp500__50mavg"
  - "c_futures_sp500__200mavg"
  - "c_futures_sp500__hoch"
  - "c_futures_sp500__pdelta"
table_name: "prep_basis_use_case"
target: "c_futures_sp500__pdelta_preview3"
models:
  lm:
    normalize:
      - "False"
      - "True"
  #knn:
  #  k:
  #    - 3
  #    - 8
  #  range: "false"