feature_list:
    #- bond_spread_mavg_600
    - c_ted_spread_credit_risk__value
    - fed_funds_rate_notrend_mavg_300
    - bond_diff_1_30_mavg_600
    - bond_diff_10_1_mavg_600
    - weeks_unemployed_notrend
    #- c_large_small_cap_ratio__value_mavg_180
    #- c_us_national_unemployment_rate__value_chanpos
    #- c_industrial_production__value_chanpos
    #- c_sp500_bonds_return_ratio__value_chanpos
    #- c_us_corporate_dept_to_gdp__value_mavg_70
    # - c_sp500_pe_ratio__value => Makes it worse without transformation
    #- return_aaa_corporate_vs_bonds_notrend
    #- m2growth_inflation_spread_mavg_90

table_name: "prepped_20210601"
target: "c_bearmarket_days__value"
models:
  #"xgboostclassifier"
  #"logisticregression"
  #linearmodel:
  #  linearmodel__normalize:
  #    - "False"
  #    - "True"
  #knn:
  #  k:
  #    - 3
  #    - 8
  #  range: "false"
  randomforestclassifier:
  #   # max_depth:
  #   #   - 5
  #   #   - 10
    randomforestclassifier__n_estimators:
      - 1000
  #xgboostregressor:
  #  xgboostregressor__eta:
  #    - 0.01
  #  xgboostregressor__max_depth:
  #    - 15
  #  xgboostregressor__booster:
  #    - 'gbtree'
  #    #- 'gblinear'
  #  xgboostregressor__min_child_weight:
  #    - 6
  # svm
  # mlpclassifier:
  #   mlpclassifier__solver:
  #     - lbfgs
  #     - adam
  #   mlpclassifier__max_iter:
  #     - 1000